source 'https://rubygems.org'
gem 'qedproject'
gem 'guard'
<% if self.sass -%>
gem 'guard-sass'
<% end -%>
<% if self.coffeescript -%>
gem 'guard-coffeescript'
<% end -%>
<% if self.jammit -%>
gem 'guard-jammit'
<% end -%>
<% if self.livereload -%>
gem 'guard-livereload'
<% end -%>

group :development do
  gem 'rb-inotify', :require => false
  gem 'rb-fsevent', :require => false
  gem 'rb-fchange', :require => false
end

